title: Christmas In The Club
description: >-
  Christmas In The Club and other hot tracks.
baseurl: ""
url: "https://christmasintheclub.com"
markdown: kramdown
collections:
  songs:
    output: false
